### PR TITLE
Docs for webhook integration target

### PR DESCRIPTION
**Pull request by jhendrick**

### CODE REVIEW

**Comment by jhendrick** [comment]
Jira issue automation is not supported in this repository. Please contact your organization administrator for more information.

**Review by ElDuderinos — APPROVED** [review]

**Comment by LiranLast** [comment]
As discussed, closing this for now.

**Comment by LiranLast** [comment]
@ElDuderinos why did you approve? Aren't we closing this area?

**Comment by ElDuderinos** [comment]
This is the only doc here that is actually right...

**Comment by LiranLast** [comment]
Closing

**Pull request closed without merging**
